//
//  HomeInterfaces.swift
//  Project
//
//  Created by Abdulkadir Oruç on 7.08.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeViewInterface: AnyObject {
    func reloadData()
    //func setPosts(_ posts: [PostModel])
    func endRefreshing()
}

protocol HomePresenterInterface: AnyObject {
    func viewDidLoad()
    func handleRefresh()
    func numberOfPosts() -> Int
    func configureCell(_ cell: CustomPostCell, for index: Int)
    func didSelectPost(at index: Int)
}

protocol HomeInteractorInputInterface: AnyObject {
    func fetchPosts()
}

protocol HomeInteractorOutputInterface: AnyObject {
    func didFetchPosts(_ posts: [PostModel])
    func didFailToFetchPosts(with error: Error)
}

protocol HomeWireframeInterface: AnyObject {
    func navigateToProfile(with userId: String)
}

