//
//  TabBarWireframe.swift
//  Project
//
//  Created by Abdulkadir Oruç on 5.08.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabBarWireframe: BaseWireframe<TabBarController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleController = TabBarController()
        super.init(viewController: moduleController)

        let presenter = TabBarPresenter(view: moduleController, wireframe: self)
        moduleController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TabBarWireframe: TabBarWireframeInterface {
    func setupViewControllers() {
        let profileWireframe = ProfileWireframe()
        
        
        let profileViewController = profileWireframe.viewController
        
        let profileNavController = UINavigationController(rootViewController: profileViewController)
        
        profileNavController.tabBarItem = UITabBarItem(title: nil, image: UIImage(systemName: "person"), selectedImage: UIImage(systemName: "person.fill"))
        
        
        viewController.setViewControllers([profileNavController])
        
        

    }
    
}
