//
//  ProfileInterfaces.swift
//  Project
//
//  Created by Abdulkadir Oruç on 3.08.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileWireframeInterface: WireframeInterface {
    
    func navigateToLoginScreen()
}

protocol ProfileViewInterface: ViewInterface {

    func showUser(with user: UserModel)
    func showError(_ message: String)
    func showLoading()
    func hideLoading()
    func updateProfileImage(_ imageUrl: String)
    func updateTabButtonsAppearance(sender: UIButton)
    func updateTabCellType(with cellType: UICollectionViewCell.Type, reuseIdentifier: String)
    func reloadCollectionView()
    func showAlert(message: String)
}

protocol ProfilePresenterInterface: PresenterInterface {
    
    func viewWillAppear()
//    func showPostDetail(forPost post: PostModel)
    func tappedLogOutButton()
    func didSelectProfileImage(image: UIImage?)
    func tappedTabButtons(_ sender:UIButton)
    
    //Collection view
    var currentCellType: String { get }
    var numberOfItems: Int { get }
    func item(at indexPath: IndexPath) -> Any
    func didSelectItem(at indexPath: IndexPath)
    func sizeForItem(at indexPath: IndexPath) -> CGSize
    func configure(cell: UICollectionViewCell, at indexPath: IndexPath)
}

protocol ProfileInteractorOutputInterface: AnyObject {

    func didFetchUserProfile(_ user: UserModel)
    func didFetchUserPosts(_ posts: [PostModel])
    func didFetchUserBooks(_ books: [BookModel])
    func onError(_ message: String)
    func didUserLogOut()
    func updateProfileImage(with imageUrl: String)
}

protocol ProfileInteractorInputInterface: AnyObject {
    
    func fetchUserProfile(for uid: String?)
    func userLogOut()
    func uploadProfileImage(user: UserModel, image: UIImage)
    func fetchUserBooks(for uid: String?)
    func fetchUserPosts(for user: UserModel?)
}
